language: generic
os:
  - linux
  - osx
sudo: false
before_install:
  - git submodule update --init --recursive
install:
  # source because it sets up env vars on some platforms
  - source travis/travis_install.sh
script: ./run_tests.py --run-all
env:
  global:
    - VIMSCRIPT=true
  matrix:
    - YCMD_PYTHON_VERSION=2.7
    - YCMD_PYTHON_VERSION=2.6
addons:
  apt:
    sources:
     - deadsnakes
    packages:
     - python2.6
     - python2.6-dev
     - python2.7
     - python2.7-dev
     - python-virtualenv
     - xterm
cache:
  directories:
    - $HOME/.cache/pip
    - /tmp/vim
